# REGLAS DEL JUEGO SUBMARINO
print("1. Preparación del juego:")
print("    - Cada jugador necesita un tablero de juego, que suele ser cuadriculado y dividido en filas y columnas numeradas.")
print("    - Cada jugador coloca sus barcos en su propio tablero sin que el oponente pueda ver su disposición.")
print("      Los barcos no pueden superponerse ni colocarse en diagonales.")
print("    - Los barcos disponibles son: un porta-aviones (5 casillas), un acorazado (4 casillas),un submarino (3 casillas)")
print("      un destructor (3 casillas) y una patrullera (2 casillas).")
print("2. Turnos:")
print("    - Los jugadores se turnan para intentar adivinar la ubicación de los barcos del oponente.")
print("    - Durante su turno, un jugador elige una casilla del tablero del oponente y la nombra, por ejemplo, \"A3\" o \"C5\".")
print("    - El oponente indica si el disparo ha sido \"agua\" (no ha tocado ningún barco) o \"tocaste\" (ha tocado parte de un barco).")
print("      Si se toca un barco, el jugador debe indicar si ha sido \"tocado\" o \"hundido\".")
print("3. Hundir lso barcos:")
print("    -Un barco se considera \"hundido\" cuando cada una de sus casillas ha sido alcanzada por disparos del oponente.")
print("    -El juego continúa hasta que todos los barcos de un jugador hayan sido hundidos.")
print("4. Ganar el juego:")
print("    -El objetivo del juego es hundir todos los barcos del oponente antes de que él hunda los tuyos.")
print("    -El primer jugador en hundir todos los barcos del oponente gana la partida.")