print("Manual para Barrer una Habitación:")
print("Objetivo: Lograr una limpieza completa y eficiente de la habitación mediante el barrido.")
print("Materiales necesarios:")
print("Escoba")
print("Recogedor")
print("Cubo con agua y detergente (opcional)")
print("Trapeador (opcional)")
print("Bolsa de basura (si es necesario)")
print("Pasos:")
print("Paso 1: Preparación")
print("Asegúrate de que la habitación esté despejada de objetos que puedan obstaculizar el barrido.")
print("Abre las ventanas para permitir la circulación de aire fresco, si es posible.")
print("Paso 2: Recoge los objetos grandes")
print("Camina alrededor de la habitación y recoge cualquier objeto grande del suelo, como juguetes, zapatos u otros artículos.")
print("Paso 3: Retira la basura")
print("Si hay basura visible en el suelo, recógela y deposítala en una bolsa de basura.")
print("Paso 4: Comienza el barrido")
print("Sujeta la escoba desde la parte superior del mango, una mano debajo de la otra con una separación aproximada de 50 cm.")
print("Con la escoba en mano, comienza a barrer desde una esquina de la habitación, moviendo la suciedad hacia el centro.")
print("Utiliza movimientos largos y firmes para barrer eficazmente toda el área.")
print("Paso 5: Presta atención a las esquinas y rincones")
print("Asegúrate de barrer cuidadosamente las esquinas y rincones de la habitación, donde la suciedad tiende a acumularse.")
print("Paso 6: Barre debajo de los muebles")
print("Si es posible, mueve los muebles ligeros y barre debajo de ellos para eliminar el polvo y la suciedad acumulada.")
print("Paso 7: Recolecta la suciedad")
print("Una vez que hayas barrido toda la habitación, utiliza el recogedor para recolectar la suciedad y los desechos del suelo.")
print("Paso 8: Deposita la suciedad")
print("Deposita la suciedad recogida en el recogedor en una bolsa de basura o en un contenedor de basura apropiado.")
print("Paso 9: Finaliza el proceso")
print("Inspecciona la habitación para asegurarte de que no quede suciedad visible en el suelo.")
print("Si es necesario, repite el barrido en áreas que puedan haber sido pasadas por alto.")
print("Paso 10: Limpieza adicional (opcional)")
print("Si deseas una limpieza más profunda, puedes trapear el suelo con agua y detergente utilizando un trapeador limpio.")
print("Paso 11: Termina la limpieza")
print("Una vez completado el barrido y, si es necesario, la limpieza adicional, guarda los materiales utilizados en su lugar correspondiente.")