print ("Pedro y Juan se encuentran en el parque local después de no verse durante un tiempo. La conversación se dirige hacia el tema de la programación, una pasión compartida por ambos. Pedro, entusiasmado por su reciente experiencia, decide compartir con Juan una emocionante oportunidad para ampliar sus conocimientos en el mundo de la programación.")
print("Pedro:- ¡Hola, Juan! ¿Cómo estás?")
print("Juan:- ¡Hola, Pedro! ¡Estoy bien, gracias! ¿Y tú?")
print("Pedro:- Bien, bien. Oye, ¿has estado pensando en aprender Python últimamente?")
print("Juan:- Sí, he escuchado sobre Python, pero no sé mucho al respecto.")
print("Pedro:- Te recomendaría que te unas a la comunidad \"Python La Paz\". Es un grupo increíble donde puedes aprender un montón sobre Python y cómo usarlo en diferentes áreas.")
print("Juan:- ¿En serio? ¿Qué tipo de cosas enseñan?")
print("Pedro:- ¡De todo! Desde lo más básico hasta cosas más avanzadas. Puedes aprender a programar aplicaciones, análisis de datos, inteligencia artificial, ¡y mucho más! Además, es una excelente manera de conocer a otras personas apasionadas por la programación.")
print("Juan:- Suena genial. ¿Cómo me uno?")
print("Pedro:- Es fácil. Solo busca \"Python La Paz\" en las redes sociales y solicita unirte al grupo. ¡Te aseguro que será una experiencia increíble y que mejorará tus habilidades de programación!")
print("Juan:- ¡Perfecto! Definitivamente lo revisaré. ¡Gracias por la recomendación, Pedro!")
print("Pedro:- No hay de qué, Juan. ¡Estoy seguro de que te encantará!")